sudo: true
language: clojure
lein: lein2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -q python3-pip
  - sudo pip3 install deadlockreporter==0.0.1
script:
  - deadlockreporter -t 300 lein test
cache:
  directories:
    - $HOME/.m2
