sudo: false
language: clojure
lein: lein2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3
    - python3-pip
before_script:
  - pip3 install deadlockreporter==0.0.1
script:
  - deadlockreporter -t 300 lein test
cache:
  directories:
    - $HOME/.m2
