sudo: false
language: clojure
lein: lein2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
# Not sure how to install python3-pip
script:
  - pip install --user deadlockreporter
  - python -m deadlockreporter -t 300 lein test
cache:
  directories:
    - $HOME/.m2
